name: Phonebook Service
on:
  push:
    branches:
      - main
      - test-workflow

  workflow_dispatch:
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Github short-commit
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      # Build the Docker image
      - name: Set version tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Deploy
        run: |-
          sed -i "s/__VERSION__/${{env.SHA}}/g" kubernetes/deployment-phonebookv2.yml

