name: Phonebook Service
on:
  push:
    branches:
      - main
      - test-workflow

  workflow_dispatch:
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@test-workflow
#      - name: Checkout
#        uses: actions/checkout@main

#     - name: Set up QEMU
#       uses: docker/setup-qemu-action@v1
    
#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1
    
    # Configure Docker with Credentials
#     - name: Configure Docker
#       run: |
#         docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
      
    # Build the Docker image
    - name: Set version tag
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

#     - name: Build and push
#       id: docker_build
#       uses: docker/build-push-action@v2
#       with:
#         context: ./
#         push: true
#         tags: ${{ secrets.SERVICE_PHONEBOOK_IMAGENAME }}:${{ steps.vars.outputs.sha_short }}

    # Setup gcloud CLI
#     - uses: google-github-actions/setup-gcloud@master
#       with:
#         project_id: ${{ secrets.GCLOUD_PROJECT }}
#         service_account_email: ${{ secrets.GCLOUD_EMAIL }}
#         service_account_key: ${{ secrets.GCLOUD_CREDENTIALS }}
#         export_default_credentials: true

    # Get the GKE credentials so we can deploy to the cluster
#     - run: |-
#         gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        ls -al
        echo ::set-output name=sha::$(git rev-parse HEAD) > version
        export VERSION=$(cat ./version)
        echo $VERSION
        sed -i "s/__VERSION__/${VERSION}/g" deployment.phonebookv2.yml

        # kubectl config set-context --current --namespace=sapawarga
        # kubectl apply -f deployment-phonebook-v2.yaml
        # kubectl get deployment,pods,service,node -o wide
