name: Phonebook Service
on:
  push:
    branches:
      - main
      - test-workflow

  workflow_dispatch:
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Github short-commit
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6
      - run: echo $SHA
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
      - run: echo $SHA
        env:
          SHA: ${{ env.SHA }}

      # Build the Docker image
      - name: Set version tag
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"


      - name: Deploy
        run: |-
          ls -al
          echo ::set-output name=sha::$(git rev-parse HEAD) > version
          export VERSION=$(cat ./version)
          echo $VERSION
          sed -i "s/__VERSION__/${VERSION}/g" deployment.phonebookv2.yml

