name: Go
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Build
      run: go build -v ./...
  # test:
  #     runs-on: ubuntu-latest
  #     strategy:
  #       fail-fast: false
  #       matrix:
  #         go: ['1.11', '1.12', '1.13', '1.14', '1.15']
  #     steps:
  #       - uses: actions/setup-go@v1
  #         with:
  #           go-version: ${{ matrix.go }}
  #       - uses: actions/checkout@v2
  #       - run: go test -v -coverprofile=profile.cov ./...
